### ISSUE TITLE
Words still censored

### ISSUE THREAD

**Issue by zetxe** [animaonline/ao3-plus-plus-feedback#1]
**Describe the bug**
When "disable word masking" is toggled on words are still censored.

**Expected behavior**
I expect that all words aren't censored.

**Screenshots**
![Screenshot_20240606_083158_AO3 ++](https://github.com/animaonline/ao3-plus-plus-feedback/assets/171939995/7d2751d2-f44b-43eb-9eaa-d8ff6966fd29)
![Screenshot_20240606_083138_AO3 ++](https://github.com/animaonline/ao3-plus-plus-feedback/assets/171939995/df04fae9-a1ba-44ba-a502-c1bd5e86d9e1)

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy Z flip 5
- OS: Android 14

**Additional context**

**Comment by animaonline** [comment]
It may appear that you saved this story to your library before enabling "Word Masking." Stories need to be re-downloaded for the "Word Masking" to be applied properly. If re-downloading doesn't help, please contact us for assistance.
