### ISSUE TITLE
Fanfiction Reader Pro for AO3 - chapters not opening

### ISSUE THREAD

**Issue by pallavimenon** [animaonline/ao3-plus-plus-feedback#12]
**Describe the bug**
All stories on the Fanfiction Reader Pro app for AO3 will not get beyond the chapter page. The message “Something went wrong” always appears. 

**To Reproduce**
1. Go to any story in the app
2. Tap on “Read” or a particular chapter heading
3. See error “Something went wrong. Try again later”

**Expected behavior**
The chapter or main story page links to the story itself. 

**Smartphone**
- Device: iPhone 15 Pro
- OS: 17.5.1
- 

![IMG_1287](https://github.com/user-attachments/assets/71f0685a-8ec3-4245-8aca-48f7cd32671d)

**Comment by animaonline** [comment]
Does this also happen when browsing the categories, or “New Stories”?

**Comment by pallavimenon** [comment]
Have tried different categories and it’s actually working fine there. Maybe
it’s only a problem for the “my library” section.

**Comment by animaonline** [comment]
Are you still having these problems when browsing your library? Could you also try removing and saving a story to see if it helps?

**Comment by blueyboo** [comment]
I am having the same issue. It works fine everywhere but the “my library” section. Deleting and re-saving does not fix the issue, for me it makes it to where it becomes unable to read in the other categories or new stories sections

**Comment by animaonline** [comment]
> I am having the same issue. It works fine everywhere but the “my library” section. Deleting and re-saving does not fix the issue, for me it makes it to where it becomes unable to read in the other categories or new stories sections

@blueyboo, may I suggest deleting your library by going to Settings and selecting ‘Delete All Stories’ to see if this helps?

**Comment by animaonline** [comment]
And another question, are you subscribed to the Pro version? @blueyboo @pallavimenon
