### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by aasaks692** [animaonline/ao3-plus-plus-feedback#3]
**Is your feature request related to a problem? Please describe.**

I have stories from Archive your own that I saved from years ago, that I want to read on here but so many stories have the same name so I can’t look it up. I would like to be able to look up a name of a work then be able to filter it by genre.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by animaonline** [comment]
Will be implemented as part of #4
