### ISSUE TITLE
Censored words

### ISSUE THREAD

**Issue by hacura** [animaonline/ao3-plus-plus-feedback#5]
**Describe the bug**
Despite creating an account and turning off the censored word setting, my stories still have them censored. Even words kids wouldn’t get in trouble for in primary school. 

**To Reproduce**
2. Tap on '....'

**Expected behavior**
I just want unfiltered content. 

**Screenshots**

**Smartphone (please complete the following information):**
- Device: iPhone 13 Pro 
- OS: [e.g. iOS 17.5.1

**Additional context**

**Comment by animaonline** [comment]
Fixed in version 1.1.2
